import { contextBridge, ipcRenderer } from 'electron';

// 设计原因：preload 只暴露受控 IPC 白名单，避免把 Node/Electron 能力直接泄漏到 renderer；
// 这也是启动回归的高风险边界，新增方法必须同步 main.ts 的 IPC 注册并补测试。
const methods: Record<string, string> = {
  pickBubbleImage:'bubble:pick', resizeBubble:'bubble:resize', listSaves:'save:list', createSave:'save:create', exportSave:'save:export', importSave:'save:import', configAdvice:'config:advice', applyConfigAdvice:'config:apply-advice', workbenchSpeech:'workbench:speech', detectConfig:'config:detect', listInstances:'instances:list', selectInstance:'instances:select', removeInstance:'instances:remove', clearInstances:'instances:clear', setInstanceVisibility:'instances:visibility', petGeometry:'pet:geometry', loadConfig:'config:load', resetPersona:'persona:reset', saveConfig:'config:save', pickPath:'dialog:pick', sendMessage:'chat:send', cancelChat:'chat:cancel', history:'history:list', deleteHistory:'history:delete', clearHistory:'history:clear', retractMessage:'history:retract', starMessage:'history:star', replayHistory:'history:replay', importVoices:'voice:import', importVoicePath:'voice:import-path', updateVoice:'voice:update', saveRecording:'recording:save', convertVoice:'voice:convert', testLlm:'llm:test', testSpeech:'speech:test', startLocalTts:'local-tts:start', stopLocalTts:'local-tts:stop', applyWeights:'local-tts:weights', exportTraining:'training:export', trainingPreflight:'training:preflight', trainingStatus:'training:status', trainingPlan:'training:plan', runTraining:'training:run', trainingJob:'training:job', cancelTraining:'training:cancel', previewTraining:'training:preview', trainingBatchProgress:'training:batch-progress', importModel:'model:import', importModelPath:'model:import-path', importAction:'action:import', importActionPath:'action:import-path', inspectWorkshop:'workshop:inspect', inspectWorkshopPath:'workshop:inspect-path', listWorkshop:'workshop:list', saveWorkshop:'workshop:save', exportWorkshop:'workshop:export', importWorkshop:'workshop:import', applyWorkshop:'workshop:apply', listVoices:'voices:list', playVoice:'voice:play', enableTools:'tools:enable', playInteraction:'interaction:play', listActions:'actions:list', listSkins:'skins:list', petSource:'pet:source', listMemories:'memory:list', addMemory:'memory:add', updateMemory:'memory:update', deleteMemory:'memory:delete', pauseMemory:'memory:pause', toggleFavorite:'favorites:toggle', healthCheck:'health:check', debugGeometry:'debug:geometry', checkTool:'tool:check', requestTool:'tool:request', confirmTool:'tool:confirm', stopTools:'tools:stop', listAudit:'audit:list', startAsr:'asr:start', stopAsr:'asr:stop', cancelAsr:'asr:cancel', startPomodoro:'alerts:start-pomodoro', stopPomodoro:'alerts:stop-pomodoro', alertsStatus:'alerts:status', testAlert:'alerts:test', spawnStoneBug:'alerts:spawn-stonebug', enemySource:'enemy:source', listEnemies:'enemies:list', importEnemy:'enemy:import', selectEnemy:'enemy:select', resourceList:'resource:list', roleFolderImport:'role-folder:import', resourceImport:'resource:import', resourceRemove:'resource:remove'
};
const sends: Record<string, string> = { openControl:'ui:open-control', addPet:'ui:pet-add', hidePet:'ui:pet-hide', closePet:'ui:pet-close', showPets:'ui:pets-show', petMenu:'ui:pet-menu', playPetAnimation:'pet:play-animation', resumePet:'pet:resume', reportHit:'pet:hit-result', reportAnimations:'pet:animations-ready', reportPetError:'pet:error', enemyHit:'enemy:hit', hoverPet:'pet:hover', dragPet:'pet:drag', manualPet:'pet:manual', audioEnded:'speech:ended', sendPcm:'asr:pcm', quit:'app:quit', reportPetContact:'pet:contact' };
const api: Record<string, any> = {};
for (const [name, channel] of Object.entries(methods)) api[name] = (...args: unknown[]) => ipcRenderer.invoke(channel, ...args);
for (const [name, channel] of Object.entries(sends)) api[name] = (...args: unknown[]) => ipcRenderer.send(channel, ...args);
api.on = (channel: string, listener: (payload: any) => void) => {
  const allowed = ['pet:surface','pet:hit-probe','instances:changed','config:changed','control:tab','pet:play-animation','pet:source-change','pet:hover-reset','pet:animations-ready','pet:direction','speech:play','speech:state','audio:stop','chat:reply','history:changed','asr:message','tools:stopped','alerts:status','system:notice'];
  if (!allowed.includes(channel)) return () => undefined;
  const handler = (_event: Electron.IpcRendererEvent, payload: any) => listener(payload);
  ipcRenderer.on(channel, handler);
  return () => ipcRenderer.removeListener(channel, handler);
};
contextBridge.exposeInMainWorld('petApi', api);

