import test from'node:test';import assert from'node:assert/strict';import{mkdtempSync,writeFileSync,readFileSync,rmSync}from'node:fs';import{tmpdir}from'node:os';import path from'node:path';import{UserVoiceLibrary}from'../src/voiceLibrary.js';import{Store,SecretStore}from'../src/store.js';import{defaults,validateConfig}from'../src/config.js';import{convertVoice,seedArguments}from'../src/voiceConvert.js';import{buildMessages}from'../src/llm.js';
test('imported voice belongs to selected character and is editable/persistent',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-custom-'));try{const f=path.join(dir,'a.wav');writeFileSync(f,Buffer.alloc(100));const v=new UserVoiceLibrary(dir);const r=v.addFile(f,'amiya','用户台词','','你好');assert.equal(v.list('other').length,0);v.update(r.id,'amiya',{textJa:'こんにちは',title:'新标题'});assert.equal(new UserVoiceLibrary(dir).list('amiya')[0].textJa,'こんにちは');}finally{rmSync(dir,{recursive:true,force:true});}});
test('saved response audio can be replayed after database restart',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-replay-'));try{let s=new Store(dir);s.turn('assistant','こんにちは',{requestId:'r1',textJa:'こんにちは',textZh:'你好'});s.attachAudio('r1',path.join(dir,'cache.wav'));s.close();s=new Store(dir);assert.equal(s.audioFor('r1'),path.join(dir,'cache.wav'));assert.equal(s.history()[0].reply.audioPath,path.join(dir,'cache.wav'));s.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('prosody conversion refuses missing RVC and never falls back to TTS',async()=>{await assert.rejects(()=>convertVoice(defaults(),'input.wav','.',new AbortController().signal),/没有调用TTS冒充/);});
test('latest role-card identity fields are included in the next system prompt',()=>{const c=defaults();c.persona={...c.persona,displayName:'名字-A',userSelfName:'用户-B',role:'身份-C',personality:'性格-D',tone:'语气-E',speechHabits:'习惯-F',addressCn:'称呼-G',addressJa:'呼び方-H'};const system=buildMessages(c,'你好',[],[])[0].content;for(const value of ['displayName','userSelfName','role','personality','tone','speechHabits','addressCn','addressJa'] as const)assert.ok(system.includes(c.persona[value]),'missing role-card field: '+value);});
test('expanded persona still fits its declared default LLM context',()=>{const c=defaults();assert.ok(c.persona.personality.length>350);const m=buildMessages(c,'你好',[],[]);assert.ok(m[0].content.includes('小提琴'));});

test('zero-shot option conditions on source pitch without automatic pitch or time changes',()=>{const v=defaults().voiceChanger;v.engine='seed-vc';const args=seedArguments(v,'source.wav','out');const val=(k:string)=>args[args.indexOf(k)+1];assert.equal(val('--f0-condition'),'True');assert.equal(val('--auto-f0-adjust'),'False');assert.equal(val('--semi-tone-shift'),'0');assert.equal(val('--length-adjust'),'1.0');});

test('LLM keys are scoped per provider endpoint, never reused on a different host',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-key-scope-'));try{const s=new SecretStore(dir,text=>Buffer.from(text).reverse(),bytes=>Buffer.from(bytes).reverse().toString());s.set('llmApiKey','old-local-test-key');s.migrateLlm('https://api.deepseek.com/v1');assert.equal(s.getLlm('https://api.deepseek.com/v1'),'old-local-test-key');assert.equal(s.getLlm('https://api.moonshot.cn/v1'),'');assert.equal(s.get('llmApiKey'),'');}finally{rmSync(dir,{recursive:true,force:true});}});

test('invalid encrypted secrets are removed without blocking config load',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-secret-recovery-'));try{const f=path.join(dir,'secrets.enc.json');writeFileSync(f,JSON.stringify({tencentSecretKey:'not-decryptable',bailianApiKey:'also-not-decryptable'}));const secrets=new SecretStore(dir,s=>Buffer.from(s),()=>{throw new Error('ciphertext belongs to an older app context');});assert.deepEqual(secrets.flags(),{llmApiKey:false,tencentSecretKey:false,bailianApiKey:false});assert.deepEqual(secrets.consumeRecoveryNotice(),['tencentSecretKey','bailianApiKey']);assert.equal(JSON.parse(readFileSync(f,'utf8')).tencentSecretKey,undefined);}finally{rmSync(dir,{recursive:true,force:true});}});
test('custom alerts and pomodoro defaults are bounded',()=>{const c=defaults();assert.equal(c.alerts.focusMinutes,25);assert.equal(c.alerts.breakMinutes,5);assert.equal(c.alerts.pomodoroCycles,4);assert.throws(()=>validateConfig({...c,alerts:{...c.alerts,focusMinutes:0}}),/专注时长/);});
test('all language modes keep Japanese display disabled while speech text pair remains available',()=>{for(const languageMode of ['ja','zh','mixed']as const){const c=defaults();c.speech.languageMode=languageMode;const m=buildMessages(c,'你好',[],[]);assert.ok(m[0].content.includes('text_ja'));assert.ok(m[0].content.includes('text_zh'));assert.equal(c.speech.showJapanese,false);}});

test('confirmed tool receipts persist with chat and do not appear pending after restart',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-tool-receipt-'));try{let s=new Store(dir);s.turn('assistant','等待确认',{requestId:'r',tools:[{id:'t',action:'open_allowed_app',args:{appId:'notepad'}}]});s.completeTool('t',{status:'success',evidence:{spawned:true}});s.close();s=new Store(dir);assert.equal(s.history()[0].reply.tools[0].status,'success');assert.ok(s.history()[0].reply.tools[0].result.includes('spawned'));s.close();}finally{rmSync(dir,{recursive:true,force:true});}});

