import { inspectWorkshopFolder, validateWorkshopProject } from '../src/workshop.js';
import {createServer} from 'node:http';import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import path from 'node:path';
import {defaults} from '../src/config.js';import {applyWeights,exportTrainingDataset} from '../src/speech.js';import {inspectModel,AssetLibrary} from '../src/assets.js';import {Store,SecretStore} from '../src/store.js';import {executeTool} from '../src/tools.js';
test('builtin library includes all bundled operators with independent profiles, Amiya originals and generated foot voice',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-assets-'));try{const lib=new AssetLibrary(path.resolve('assets/builtin'),dir).scan();assert.ok(lib.bundles.length>=12);assert.ok(Object.keys(lib.profiles).length>=2);assert.equal(lib.bundles.filter(b=>b.operatorId==='Amiya').length,12);assert.equal(lib.voices.filter(v=>v.operatorId==='Amiya'&&v.source!=='generated').length,38);assert.ok(lib.voices.some(v=>v.id==='foot_poke'&&v.source==='generated'));assert.ok(lib.actions(defaults()).length>=20);const special=lib.actions({...defaults(),ui:{...defaults().ui,selectedSkin:'Amiya-播种者'}});assert.ok(special.some(a=>a.name==='Special'));}finally{rmSync(dir,{recursive:true,force:true});}});
test('GPT and SoVITS selection use exact official weight endpoints',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-weight-'));const calls:string[]=[];const s=createServer((q,r)=>{calls.push(q.url||'');r.end('success');});await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));try{const g={...defaults().speech.gptSovits,apiUrl:'http://127.0.0.1:'+(s.address()as any).port,gptModelPath:path.join(dir,'a.ckpt'),sovitsModelPath:path.join(dir,'a.pth')};writeFileSync(g.gptModelPath,'test');writeFileSync(g.sovitsModelPath,'test');await applyWeights(g,new AbortController().signal);assert.ok(calls[0].startsWith('/set_gpt_weights?weights_path='));assert.ok(calls[1].startsWith('/set_sovits_weights?weights_path='));}finally{s.closeAllConnections();await new Promise(r=>s.close(r));rmSync(dir,{recursive:true,force:true});}});
test('multiple training references export exact labeled list, incomplete rows refuse',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-data-'));try{const c=defaults();const file=path.join(dir,'ref.wav');writeFileSync(file,'test');c.speech.gptSovits.trainingReferences=[{audioPath:file,text:'こんにちは',language:'ja'},{audioPath:file,text:'博士',language:'zh'}];const r=exportTrainingDataset(c,dir);assert.equal(r.count,2);assert.match(readFileSync(r.list,'utf8'),/\|amiya\|JA\|こんにちは/);c.speech.gptSovits.trainingReferences[0].text='';assert.throws(()=>exportTrainingDataset(c,dir));}finally{rmSync(dir,{recursive:true,force:true});}});
test('selected model directory import copies owned model; incomplete foreign files reject',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-import-'));try{const lib=new AssetLibrary(path.resolve('assets/builtin'),dir).scan();const b=lib.importFolder(path.resolve('assets/builtin/干员模型/Amiya/Amiya-原皮/基建'));assert.ok(b.customId);assert.equal(b.animations.length,6);assert.throws(()=>inspectModel(path.join(dir,'no.skel')));}finally{rmSync(dir,{recursive:true,force:true});}});
test('secrets cannot fall back into plaintext config',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-secret-'));try{const secrets=new SecretStore(dir,s=>Buffer.from(Buffer.from(s).map(x=>x^123)),b=>Buffer.from(b.map(x=>x^123)).toString());secrets.set('llmApiKey','testing-only-not-a-real-key');assert.ok(!readFileSync(secrets.file,'utf8').includes('testing-only'));assert.equal(secrets.get('llmApiKey'),'testing-only-not-a-real-key');const store=new Store(dir);store.saveConfig(defaults());assert.ok(!JSON.stringify(store.config()).includes('testing-only'));store.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test('allowed file tools execute/verify and stop flag rejects writes',async()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-tools-'));try{const p={...defaults().permissions,enabled:true,emergencyStop:false,allowedDirectories:[dir]};const file=path.join(dir,'safe.txt');const r=await executeTool({action:'write_allowed_file_with_confirmation',args:{path:file,content:'博士'}},p,new AbortController().signal);assert.equal(r.evidence?.contentMatches,true);const read=await executeTool({action:'read_allowed_file',args:{path:file}},p,new AbortController().signal);assert.equal(read.evidence?.text,'博士');await assert.rejects(()=>executeTool({action:'write_allowed_file_with_confirmation',args:{path:file,content:'blocked'}},{...p,emergencyStop:true},new AbortController().signal));}finally{rmSync(dir,{recursive:true,force:true});}});

test('camera profiles share a fixed normalized scale across front and build, excluding Start root travel',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-camera-'));try{const l=new AssetLibrary(path.resolve('assets/builtin'),dir).scan();for(const operator of new Set(l.bundles.map(b=>b.operatorId))){for(const skin of new Set(l.bundles.filter(b=>b.operatorId===operator).map(b=>b.skin))){const a=l.bundles.filter(b=>b.operatorId===operator&&b.skin===skin&&b.view!=='背面');if(a.length>=2){assert.deepEqual(a[0].source.camera.bounds,a[1].source.camera.bounds);assert.ok(Number.isFinite(a[0].source.camera.bounds.maxY)&&a[0].source.camera.bounds.maxY>a[0].source.camera.bounds.minY,'camera bounds must remain finite and non-empty');}}}}finally{rmSync(dir,{recursive:true,force:true});}});


test('all-animation fitting measures instantaneous size, not whole-model travel distance',()=>{const file=path.resolve('assets/builtin/干员模型/Angelina the Mellow Wish/Angelina the Mellow Wish-原皮/正面/char_1015_aglna2.skel');const model=inspectModel(file);assert.ok(model.camera.fitBounds,'full animation fitting bounds must be measured');assert.ok(model.camera.fitBounds.maxY<2.4,'root travel must not make a normal standing character tiny');assert.ok(model.camera.bounds.maxY>3,'retain original motion range as separate audit evidence');});

test('invisible special-effect attachments do not shrink the entire skin camera',()=>{const model=inspectModel(path.resolve('assets/builtin/干员模型/Exusiai/Exusiai-午夜邮差/基建/build_char_103_angel_sale_8.skel'));assert.ok(model.camera.fitBounds);assert.ok(model.camera.fitBounds.maxX-model.camera.fitBounds.minX<10,'hidden off-stage particles must not count as visible model size');});

test('every autogenerated role card fits the default context budget before any network call',async()=>{const {buildMessages}=await import('../src/llm.js');const dir=mkdtempSync(path.join(tmpdir(),'terra-card-budget-'));try{const lib=new AssetLibrary(path.resolve('assets/builtin'),dir).scan();for(const [id,p]of Object.entries(lib.profiles) as Array<[string,any]>){if(id==='Amiya')continue;const c=defaults();c.persona={...c.persona,id:'operator:'+id,examples:[],displayName:p.name,role:p.role,personality:p.personality,tone:'根据该角色档案与语音保持自然、符合角色的语气；用户可以继续编辑。',speechHabits:p.speechHabits};assert.doesNotThrow(()=>buildMessages(c,'你好',[],[]),id+' default role card is too large');}}finally{rmSync(dir,{recursive:true,force:true});}});

test('only exact untouched autogenerated cards are refreshed, edited cards stay intact',async()=>{const {migrateBuiltinPersonas}=await import('../src/personaMigration.js');const c=defaults();c.assets.customId="operator:Kal'tsit";c.persona={...c.persona,personality:'old exact card'};c.profiles={"operator:Kal'tsit":{persona:{...c.persona,personality:'user edited old exact card'}},'operator:Suzuran':{persona:{...c.persona,personality:'old Suzuran card'}}};const next=migrateBuiltinPersonas(c,{"Kal'tsit":{legacyPersonality:'old exact card',personality:'new concise card'},Suzuran:{legacyPersonality:'old Suzuran card',personality:'new Suzuran card'}});assert.equal(next.persona.personality,'new concise card');assert.equal(next.profiles["operator:Kal'tsit"].persona.personality,'user edited old exact card');assert.equal(next.profiles['operator:Suzuran'].persona.personality,'new Suzuran card');assert.equal(c.persona.personality,'old exact card');});

test('action import is role-bound, copied into user data, and exposes only compatible non-static actions',()=>{const dir=mkdtempSync(path.join(tmpdir(),'amiya-action-import-'));try{const lib=new AssetLibrary(path.resolve('assets/builtin'),dir).scan();const c=defaults();const target=lib.selected(c);assert.ok(target);const result=lib.importActionFolder(path.resolve('assets/builtin/干员模型/Amiya/Amiya-原皮/基建'),{bundleId:target.id,operatorId:target.operatorId,skin:target.skin});assert.ok(result.animationNames.includes('Interact'));assert.ok(lib.actions(c).some((a:any)=>a.imported&&a.importId===result.id));assert.ok(existsSync(path.join(dir,'actions',result.id,'manifest.json')));assert.throws(()=>lib.importActionFolder(path.resolve('assets/builtin/干员模型/Amiya/Amiya-播种者/基建'),{bundleId:target.id,operatorId:target.operatorId,skin:target.skin}),/骨骼或插槽/);}finally{rmSync(dir,{recursive:true,force:true});}});



test('workshop preflight distinguishes local format from runnable capabilities', () => {
 const dir=mkdtempSync(path.join(tmpdir(),'workshop-preflight-')); try {
  writeFileSync(path.join(dir,'avatar.model3.json'),'{}'); writeFileSync(path.join(dir,'tex.png'),'x');
  const live=inspectWorkshopFolder(dir); assert.equal(live.format,'live2d'); assert.equal(live.ready,false); assert.equal(live.capabilities.actions,false);
  const invalid=inspectWorkshopFolder(mkdtempSync(path.join(tmpdir(),'workshop-empty-'))); assert.equal(invalid.format,'unknown'); assert.equal(invalid.ready,false);
  assert.deepEqual(validateWorkshopProject({schemaVersion:1,id:'x',roleId:'r',displayName:'x',sourceFormat:'spine3.8',sourceFolder:'',targetBundleId:'b',actionMappings:{idle:'',deployment:'',interact:'',move:''},capabilities:{actions:true,deployment:true,idle:true,collision:true,chase:true,voiceBinding:false},createdAt:'',updatedAt:''}),[]);
 } finally { rmSync(dir,{recursive:true,force:true}); }
});
