// @ts-nocheck — fixture uses the bundled untyped Spine 3.8 runtime, as do the existing geometry tests.
// The preview has a separate body ruler because authored slot aliases must not silently change native pet contact geometry.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import spine from '../../../apps/desktop/src/pet/vendor/spine-webgl.js';
const modulePath=new URL('../src/previewGeometry.ts',import.meta.url);
async function preview(){assert.ok(fs.existsSync(modulePath),'preview-only geometry policy must exist');return import('../src/previewGeometry.js');}
function roleSkeleton(role:string,stem:string){const base=`assets/builtin/干员模型/${role}/${role}-原皮/基建/${stem}`,text=fs.readFileSync(base+'.atlas','utf8'),size=text.match(/size:\s*(\d+)\s*,\s*(\d+)/)!;const texture={setFilters(){},setWraps(){},getImage(){return{width:+size[1],height:+size[2]}}};const data=new spine.SkeletonBinary(new spine.AtlasAttachmentLoader(new spine.TextureAtlas(text,()=>texture))).readSkeletonData(new Uint8Array(fs.readFileSync(base+'.skel')));const sk=new spine.Skeleton(data);if(data.defaultSkin)sk.setSkin(data.defaultSkin);const st=new spine.AnimationState(new spine.AnimationStateData(data));st.setAnimation(0,'Relax',true);st.apply(sk);sk.updateWorldTransform();return sk;}
test('preview includes Beagle shoes and leg aliases but excludes weapons and effects',async()=>{const {previewBodySlot}=await preview();for(const n of ['F_L_Shoes','F_R_Bigleg','F_L_Smallleg','F_C_Head'])assert.equal(previewBodySlot(n),true,n);for(const n of ['F_Shield','F_Weapon_Foot','F_FX_Bigleg','F_Ear'])assert.equal(previewBodySlot(n),false,n);});
test('Beagle preview ruler reaches actual shoes, not the waist',async()=>{const {measurePreviewBody}=await preview(),sk=roleSkeleton('Beagle','build_char_122_beagle'),attachments=sk.slots.map((s:any)=>s.attachment),b=measurePreviewBody(sk);assert.ok(b.bottom<1,'shoes must define the standing floor');assert.ok(b.height>350&&b.height<390,'full standing head-to-shoes height');assert.deepEqual(sk.slots.map((s:any)=>s.attachment),attachments,'measurement must restore original attachments');});
test('existing Amiya preview ruler stays unchanged',async()=>{const {measurePreviewBody}=await preview(),{measureBody}=await import('../src/bodyGeometry.js'),sk=roleSkeleton('Amiya','build_char_002_amiya');assert.deepEqual(measurePreviewBody(sk),measureBody(sk));});
test('control opts in to larger preview sizing without changing native caller geometry',()=>{const control=fs.readFileSync('apps/desktop/src/renderer/control.ts','utf8');assert.match(control,/previewOnly\s*:\s*true/);for(const file of ['apps/desktop/src/renderer/pet.ts','apps/desktop/src/renderer/enemy.ts'])assert.doesNotMatch(fs.readFileSync(file,'utf8'),/previewOnly\s*:\s*true/);});

test('preview recognizes authored Chinese limb names and robot wheels, not their effects',async()=>{const {previewBodySlot,measurePreviewBody}=await preview();for(const n of ['F_R_Xiaotui','F_R_Datui','F_L_Xiezi','F_Kua','F_Chassis','F_L_Wheel'])assert.equal(previewBodySlot(n),true,n);assert.equal(previewBodySlot('F_Effect_Wheel'),false);const b=measurePreviewBody(roleSkeleton('Warfarin','build_char_171_bldsk'));assert.ok(b.bottom<5&&b.height>300,'Warfarin feet cannot be mistaken for the waist');});

test('oversized preview accessories enlarge drawable space but never reduce body scale',async()=>{const {previewFrame,PREVIEW_SIZE}=await preview();const small=previewFrame(350,PREVIEW_SIZE.bodyHeight,{left:100,right:100,top:400,bottom:0}),wide=previewFrame(350,PREVIEW_SIZE.bodyHeight,{left:1400,right:1600,top:500,bottom:600});assert.equal(small.scale,wide.scale);assert.equal(wide.scale*350,280);assert.ok(wide.width>2000&&wide.height>800);assert.ok(wide.anchor.x>1400*wide.scale);assert.ok(wide.anchor.y>600*wide.scale);});

test('alternate authored Idle_A is a preview standby, not an attack or a summon idle',async()=>{const {previewStandbyName}=await preview();assert.equal(typeof previewStandbyName,'function','preview standby chooser must exist');assert.equal(previewStandbyName(['Attack_A','Default_A','Idle_A','Idle_B']),'Idle_A');assert.equal(previewStandbyName(['Doll_Idle','B_Idle','Idle']),'Idle');});
