import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';
import {defaults} from '../src/config.js';import {roleReferenceConfig,roleTrainingReferences} from '../src/roleSpeech.js';import {exportTrainingDataset} from '../src/speech.js';
// Use a tiny owned catalog to reproduce reference-language and cross-role isolation failures deterministically.
function fixture(){const root=fs.mkdtempSync(path.join(tmpdir(),'terra-role-reference-'));for(const r of ['A','B']){fs.mkdirSync(path.join(root,'干员语音',r),{recursive:true});fs.writeFileSync(path.join(root,'干员语音',r,'cn_001.mp3'),'contract fixture');}const refs={roles:{A:{languages:{ja:{main:'干员语音/A/cn_001.mp3',aux:[],samples:[{audio:'干员语音/A/cn_001.mp3',text:'こんにちは',language:'ja'}]}}},B:{languages:{ja:{main:'干员语音/B/cn_001.mp3',aux:[],samples:[{audio:'干员语音/B/cn_001.mp3',text:'',language:'ja'}]}}}}};fs.writeFileSync(path.join(root,'role-reference-catalog.json'),JSON.stringify(refs));return root;}
test('main reference original text is filled and previous role builtin training rows are removed',()=>{const root=fixture();try{const c=defaults();c.assets.customId='operator:A';const a=roleReferenceConfig(c,root,'ja');assert.equal(a.speech.gptSovits.promptText,'こんにちは');a.assets.customId='operator:B';const b=roleReferenceConfig(a,root,'ja');assert.equal(b.speech.gptSovits.trainingReferences.length,1);assert.ok(b.speech.gptSovits.trainingReferences[0].audioPath.includes('/B/'));assert.equal(b.speech.gptSovits.promptText,'');assert.equal(b.speech.gptSovits.trainingReferences[0].text,'');assert.throws(()=>exportTrainingDataset(roleReferenceConfig(b,root,'ja',true),root),/非空原文/);}finally{assert.equal(path.dirname(path.resolve(root)),path.resolve(tmpdir()),'cleanup must stay inside temporary root');fs.rmSync(root,{recursive:true,force:true});}});
test('explicit user samples stay edited and builtin URI materializes only for export',()=>{const root=fixture();try{const c=defaults();c.assets.customId='operator:A';c.speech.gptSovits.trainingReferences=[{audioPath:'builtin:干员语音/A/cn_001.mp3',text:'手动修订',language:'ja'}];const prepared=roleReferenceConfig(c,root,'ja',true);assert.equal(prepared.speech.gptSovits.trainingReferences[0].text,'手动修订');assert.ok(fs.existsSync(prepared.speech.gptSovits.trainingReferences[0].audioPath));const cross=roleReferenceConfig(c,root,'zh');assert.equal(cross.speech.gptSovits.language,'zh');assert.equal(cross.speech.gptSovits.promptLanguage,'ja');assert.ok(cross.speech.gptSovits.referenceAudioPath.includes('/A/'));c.assets.customId='operator:Missing';assert.throws(()=>roleReferenceConfig(c,root,'zh'),/缺少所选语言/);}finally{assert.equal(path.dirname(path.resolve(root)),path.resolve(tmpdir()),'cleanup must stay inside temporary root');fs.rmSync(root,{recursive:true,force:true});}});
test('bundled samples use the recording language original, never translated text',()=>{const root=path.resolve('assets/builtin'),ref=JSON.parse(fs.readFileSync(path.join(root,'role-reference-catalog.json'),'utf8')),original=JSON.parse(fs.readFileSync(path.join(root,'role-transcript-catalog.json'),'utf8'));for(const [role,r]of Object.entries(ref.roles)as any){for(const sample of r.languages.ja.samples){if(sample.text&&sample.transcriptSource==='prts_language_labelled_original'){assert.equal(sample.text,original.roles[role]?.languages?.[sample.language]?.[path.basename(sample.audio)],role+' transcript not an exact labelled original');}else if(sample.text){assert.equal(sample.transcriptSource,'local_whisper_small_unreviewed');const c=defaults();c.assets.customId='operator:'+role;const row=roleTrainingReferences(c,root,'ja').find(r=>r.audioPath.endsWith(sample.audio));assert.equal(row?.needsReview,true);assert.equal(row?.reviewed,false);}else assert.equal(sample.transcriptSource,'missing_original');}}});

// English collaboration recordings and Chinese-only source recordings use their
// own reference language while the user's selected output remains ja/zh.
test('verified native recording language drives prompt and training labels, not output mode',()=>{
 const root=path.resolve('assets/builtin');for(const [role,language]of [['Iana','en'],['Frost','en'],['Fuze','en'],['Tachanka','en'],['Nine-Colored Deer','zh']]){
 const c=defaults();c.assets.customId='operator:'+role;const out=roleReferenceConfig(c,root,'ja');
 assert.equal(out.speech.gptSovits.promptLanguage,language);assert.equal(out.speech.gptSovits.language,'ja');
 assert.ok(out.speech.gptSovits.trainingReferences.every(row=>row.language===language));
 }
});
