// @ts-nocheck
import {Microphone} from './microphone.js';
import {isFavorite} from '../../../../services/core/src/favorites.js';
import {selectableActions} from '../../../../services/core/src/animationChoices.js';
export function setupLocalPanels(api,root,readConfig){let panel=null,busy=false;const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const microphone=new Microphone(null,{text:t=>{panel?.querySelector('.local-status')?.replaceChildren(document.createTextNode(t));},level:()=>{},state:t=>{if(panel)panel.querySelector('.local-status').textContent=t;},complete:t=>void send(t),error:t=>status(t)});
 const status=text=>{const el=panel?.querySelector('.local-status');if(el)el.textContent=text;};
 async function send(text){if(busy||!text?.trim())return;busy=true;status('等待本角色回复…');try{const r=await api.sendMessage(text);status(r.textZh);}catch(e){status(e.message);}finally{busy=false;}}
 async function open(kind){if(kind==='close'){api.closePet();return;}panel?.remove();panel=document.createElement('div');api.hoverPet(true);panel.addEventListener('pointerdown',e=>e.stopPropagation());panel.className='pet-local-panel';panel.innerHTML='<button class="local-close" aria-label="关闭快捷面板">×</button><div class="local-status" role="status"></div>';root.querySelector('.pet-root').append(panel);panel.style.left=root.style.getPropertyValue('--local-panel-x')||'20px';panel.style.top=root.style.getPropertyValue('--local-panel-y')||'20px';panel.querySelector('.local-close').onclick=()=>{void microphone.cancel();panel.remove();panel=null;api.hoverPet(false);};
 const loaded=await api.loadConfig();const role=loaded.config.assets.customId||'builtin';const fav=(type,id)=>isFavorite(loaded.config.favorites,type,id,role);// Favorites must sort before ordinary items; comparing a's rank against b's rank avoids the previous reversed order.
 const order=(items,type)=>[...items].sort((a,b)=>(fav(type,a.id)?-1:0)-(fav(type,b.id)?-1:0)||String(a.id).localeCompare(String(b.id)));if(kind==='chat'||kind==='mic'){panel.insertAdjacentHTML('beforeend','<form class="local-compose"><textarea name="text" rows="3" maxlength="8000" placeholder="和当前角色说话…"></textarea><button>发送</button></form><button class="local-mic">语音输入 / 结束</button>');panel.querySelector('form').onsubmit=e=>{e.preventDefault();void send(new FormData(e.target).get('text'));};panel.querySelector('.local-mic').onclick=async()=>{try{if(microphone.active)await microphone.finish();else await microphone.start(loaded.config.speech.tencentAsr,loaded.secretFlags);}catch(e){status(e.message);}};if(kind==='mic')panel.querySelector('.local-mic').click();else panel.querySelector('textarea').focus();}
 else{const items=order(kind==='actions'?selectableActions(await api.listActions()):loaded.voices,kind==='actions'?'action':'voice');panel.insertAdjacentHTML('beforeend','<select multiple size="6" class="local-list">'+items.map(x=>'<option value="'+esc(x.id)+'">'+esc((fav(kind==='actions'?'action':'voice',x.id)?'★ ':'')+(kind==='actions'?x.group+' · '+x.displayName:x.title))+'</option>').join('')+'</select><button class="local-play">播放所选随机一条</button>');panel.querySelector('.local-play').onclick=async()=>{const ids=[...panel.querySelector('select').selectedOptions].map(o=>o.value);if(!ids.length){status('请先选一条或按Ctrl多选');return;}const id=ids[Math.floor(Math.random()*ids.length)];if(kind==='actions')api.playPetAnimation({id,loop:false});else try{const r=await api.playVoice(id);status(r.textZh);}catch(e){status(e.message);}};}
 }
 api.on('speech:play',()=>{if(microphone.active)void microphone.cancel();});return {open};
}
