// @ts-nocheck
export function outputPage(state,h){
 const {input,area,select,toggle,btn,keyField,esc}=h;
 const c=state.config.speech,g=c.gptSovits,b=c.bailian;
 const key=(state.config.assets.customId||'Amiya').replace(/^operator:/,'')||'Amiya';
 const trained=state.config.voiceTraining?.[key];
 const refs=Array.isArray(g.trainingReferences)?g.trainingReferences:[];
 // Training completion and human timbre validation are separate; completed real weights must never be described as missing data.
 const statusNames={not_started:'尚未开始',dataset_ready:'数据已准备',training:'正在训练',trained_unverified:'已训练 · 待独立试听',verified:'已验证',failed:'训练失败'};
 const trainedLabel=trained?.status==='verified'?'已训练语音（已验证）':trained?.status==='trained_unverified'?'已训练语音（待独立试听验证）':'已训练语音（尚未就绪）';
 const statusText={verified:'当前角色专属GPT/SoVITS权重已通过独立验证，可以作为输出路线。',dataset_ready:'已生成当前角色的训练清单，尚未执行训练。',training:'当前角色正在执行真实本机训练；完成前不会假称产物已验证。',trained_unverified:'真实训练权重已经存在并自动填写到下方；可试听，但人工音色相似度尚未确认。',failed:'当前角色训练失败，请查看真实训练日志；不会使用假权重替代。',not_started:'尚未开始当前角色专属训练；辅助参考只用于推理，不等于训练。'}[trained?.status||'not_started'];
 const trainingRows=refs.length?refs.map((r,i)=>`<div class="training-row" data-index="${i}"><strong>${esc(r.audioPath)}</strong>${input('trainingText'+i,'准确原文',r.text||'')}${select('trainingLang'+i,'语言',r.language||'ja',[['ja','日语'],['zh','中文'],['en','英语'],['ko','韩语'],['yue','粤语']])}${r.needsReview?'<p class="notice warning">这是本地识别候选，不是已校对原文。请核对录音和语言；未确认前禁止训练导出。</p>'+toggle('trainingReviewed'+i,'我已核对该录音的原文与语言',r.reviewed===true):''}${btn('training-remove','移除',`data-index="${i}"`)}</div>`).join(''):'<p class="fine-print">'+(trained?.samples?.length?'训练档案已有 '+trained.samples.length+' 条样本。当前编辑列表为空不表示没有训练数据；重新添加录音并保存会生成新的独立训练任务。':'尚未加入训练样本。请先选择录音，再为每条录音填写逐字原文和语言。')+'</p>';
 return `<form id="speech-output-form">
 <div class="card"><h4>声音输出 · ${esc(state.config.persona.displayName)}</h4><p>本地GPT-SoVITS支持参考音频条件推理；“已训练语音”只允许当前角色专属权重通过独立验证后使用，二者不能混称。</p>${select('languageMode','发声语言',c.languageMode,[['ja','日语'],['zh','中文'],['mixed','中日轮换']])}${select('outputMode','输出路线',c.outputMode,[['gpt-sovits','本地GPT-SoVITS · 参考推理'],['trained-voice',trainedLabel],['text-only','只显示字幕'],['bailian','百炼云语音']])}${toggle('replyEnabled','启用语音回复',c.replyEnabled)}${toggle('showText','聊天文字',c.showText)}${toggle('subtitlesEnabled','角色旁中文字幕',c.subtitlesEnabled)}${toggle('showChinese','显示中文',c.showChinese)}${input('subtitleSize','字号',c.subtitleSize,'number','','min="10" max="30"')}</div>
 <div class="card"><h4>本地GPT-SoVITS · 参考推理</h4><div class="toolbar">${btn('detect-config','帮忙识别环境 / Python / 共用权重','data-section="local-tts"')}${btn('assist-config','AI帮我填写（先预览）','data-section="local-tts"')}${btn('local-tts-start','启动本地服务')}${btn('local-tts-stop','停止本软件的服务')}</div>${toggle('sovitsEnabled','启用本地合成',g.enabled)}${input('apiUrl','本地API地址',g.apiUrl)}${select('device','设备',g.device,[['auto','自动CPU/CUDA'],['cpu','CPU'],['cuda','CUDA（需可用显卡）']])}<details><summary>高级环境 / 共用权重（一般不必修改）</summary>${input('installPath','完整环境',g.installPath)}${btn('pick','选择环境','data-target="installPath" data-kind="directory"')}${input('pythonPath','Python（自动识别）',g.pythonPath)}${btn('pick','选择Python','data-target="pythonPath" data-kind="program"')}${input('gptModelPath','共用GPT.ckpt',g.gptModelPath)}${btn('pick','选择共用GPT','data-target="gptModelPath" data-kind="gpt"')}${input('sovitsModelPath','共用SoVITS.pth',g.sovitsModelPath)}${btn('pick','选择共用SoVITS','data-target="sovitsModelPath" data-kind="sovits"')}${btn('apply-weights','应用已保存权重')}</details><p class="fine-print">这里的辅助录音是推理时参考，不会自动进入训练。</p></div>
 <div class="card"><h4>角色语音训练档案 · ${esc(trained?.displayName||state.config.persona.displayName)}</h4><p class="notice warning">${statusText}</p><p>状态：<strong>${esc(statusNames[trained?.status||'not_started'])}</strong> · 训练档案样本：${trained?.samples?.length||0} 条 · 当前编辑列表：${refs.length} 条。只有完成真实本地训练、独立试听并通过验证，才允许切换“已训练语音”。</p><div class="toolbar">${btn('training-pick','添加训练录音（多选）')}${btn('training-preflight','训练环境只读预检')}${btn('training-export','导出训练清单')}${btn('training-run','开始本机真实训练')}${btn('training-job','查看训练进度/接入产物')}${btn('training-preview','试听真实训练模型（未验证）')}${btn('training-batch-progress','查看全角色训练队列')}${btn('training-cancel','停止本软件训练')}${btn('training-start','仅登记外部训练开始')}${btn('training-complete','登记训练完成（待验证）')}${btn('training-verify','登记独立验证通过')}${btn('training-plan','生成官方阶段计划')}</div><div id="training-rows">${trainingRows}</div>${input('trainedGptPath','角色专属GPT权重',trained?.trainedGptModelPath||'')}${btn('pick','选择角色专属GPT','data-target="trainedGptPath" data-kind="gpt"')}${input('trainedSovitsPath','角色专属SoVITS权重',trained?.trainedSovitsModelPath||'')}${btn('pick','选择角色专属SoVITS','data-target="trainedSovitsPath" data-kind="sovits"')}<p class="fine-print">填入路径不会自动标记完成；训练任务和独立验证必须产生可追溯记录。未验证权重不会进入部署或创意工坊默认语音。</p></div>
 <div class="card"><h4>当前角色参考录音</h4>${toggle('autoLanguageReference','自动使用本角色主参考及全部辅助',c.autoLanguageReference)}${btn('detect-config','帮忙识别本角色参考','data-section="references"')}${btn('pick-reference-set','选择主参考和辅助（多选）')}${input('referenceAudioPath','主参考（3–10秒）',g.referenceAudioPath)}${area('auxReferences','辅助参考（选完自动填入）',g.auxReferenceAudioPaths.join('\n'))}${btn('pick-audios','多选辅助参考')}<details><summary>可选原文与语言</summary>${area('promptText','准确原文，可留空',g.promptText)}${select('promptLanguage','参考语言',g.promptLanguage,[['ja','日语'],['zh','中文'],['en','英语']])}${input('speed','语速',g.speed,'number','','min=".5" max="2" step=".05"')}</details></div>
 <div class="card"><h4>百炼云输出</h4>${toggle('bailianEnabled','启用百炼',b.enabled)}${btn('detect-config','帮忙识别地域端点','data-section="bailian"')}${btn('assist-config','AI帮我填写（先预览）','data-section="bailian"')}${keyField('bailianApiKey','百炼API Key',state.flags.bailianApiKey)}${select('region','地域',b.region,[['cn-beijing','中国北京'],['ap-southeast-1','新加坡'],['us-east-1','美国弗吉尼亚']])}${input('bailianBaseUrl','官方TTS端点',b.baseUrl)}${input('bailianModel','语音模型',b.model)}${input('voiceId','音色/自有音色ID',b.voiceId)}${select('bailianLanguage','输出语言',b.language,[['Japanese','日语'],['Chinese','中文']])}${input('dailyCharBudget','每日字符上限',b.dailyCharBudget,'number')}${input('monthlyCharBudget','每月字符上限',b.monthlyCharBudget,'number')}<p>账号权限和专属音色ID不能自动猜测；预设Cherry不是当前角色声线。</p></div><div class="toolbar"><button type="submit" class="primary">保存声音输出</button>${btn('test-speech','试听当前输出')}</div></form>`;
}export function inputPage(state,h){const {input,select,toggle,btn,keyField}=h,t=state.config.speech.tencentAsr;return `<form id="speech-input-form" class="card"><h4>语音输入 · 腾讯识别</h4><p>输入和角色发声是两个独立模块。只有点击麦克风才录音；播放期间停止输入，避免回声。</p>${btn('detect-config','帮忙识别输入设置','data-section="asr"')}${btn('assist-config','AI帮我填写（先预览）','data-section="asr"')}${toggle('asrEnabled','启用识别',t.enabled)}${input('appId','腾讯AppID',t.appId)}${input('secretId','腾讯SecretID',t.secretId)}${keyField('tencentSecretKey','腾讯SecretKey',state.flags.tencentSecretKey)}${select('engine','引擎',t.engine,[['16k_zh','中文'],['16k_ja','日语'],['16k_en','英语']])}${input('silenceMs','静音结束毫秒',t.silenceMs,'number')}${input('volumeThreshold','RMS门限',t.volumeThreshold,'number','','step=".001"')}${input('maxRecordingMs','最长录音毫秒',t.maxRecordingMs,'number')}${toggle('continueAfterReply','回复后允许继续录音',t.continueAfterReply)}<p>需要麦克风授权和腾讯账号服务权限；未配置不开网络。</p></div><div class="card"><h4>可选外部实时语音适配器</h4><div class="toolbar">${btn('detect-config','帮忙识别适配器','data-section="external-realtime"')}</div><p>这里是统一适配配置入口，可接入其他本地实时语音软件或你自己的 WebSocket/HTTP 服务。保存配置不会假称已连接；只有真正实现并通过协议握手后才会显示就绪。程序路径、工作目录和参数只保存在本机，不会发送给 AI。</p>${toggle('externalRealtimeEnabled','启用外部适配器',state.config.speech.externalRealtime.enabled)}${input('externalProviderLabel','适配器名称',state.config.speech.externalRealtime.providerLabel)}${select('externalTransport','传输协议',state.config.speech.externalRealtime.transport,[['websocket','WebSocket'],['http','HTTP']])}${input('externalEndpoint','服务地址',state.config.speech.externalRealtime.endpoint)}${input('externalExecutablePath','可选启动程序',state.config.speech.externalRealtime.executablePath)}${btn('pick','选择启动程序','data-target="externalExecutablePath" data-kind="program"')}${input('externalWorkingDirectory','工作目录',state.config.speech.externalRealtime.workingDirectory)}${btn('pick','选择工作目录','data-target="externalWorkingDirectory" data-kind="directory"')}${input('externalArguments','启动参数',state.config.speech.externalRealtime.arguments,'text','仅作为参数记录；不会拼接成任意Shell。')}${toggle('externalAutoStart','显示时自动启动外部程序',state.config.speech.externalRealtime.autoStart)}${select('externalInputFormat','送入音频格式',state.config.speech.externalRealtime.inputFormat,[['pcm16','PCM16'],['wav','WAV']])}${select('externalOutputFormat','返回消息格式',state.config.speech.externalRealtime.outputFormat,[['json','JSON'],['text','纯文本']])}<p class="fine-print">当前版本仍使用腾讯实时 ASR 作为已实现输入链路；外部适配器先完成配置隔离和协议占位，未连接的软件不会被误报为可用。</p></div><button class="primary" type="submit">保存输入设置</button></form>`;}
export function workbenchPage(state,h){const {input,area,select,toggle,btn}=h,v=state.config.voiceChanger,g=state.config.speech.gptSovits;return `<div class="card"><h4>语音工作台</h4><p>文本合成是TTS，保留语调转换是音频到音频，不能互相冒充。</p>${btn('detect-config','帮忙识别工作台','data-section="workbench"')}${btn('assist-config','AI帮我填写（先预览）','data-section="workbench"')}</div><form id="workbench-tts-form" class="card"><h4>多参考文本合成</h4>${area('workbenchText','合成文字','')}${select('workbenchLanguage','语言','ja',[['ja','日语'],['zh','中文']])}${input('referenceAudioPath','主参考',g.referenceAudioPath)}${area('auxReferences','辅助参考',g.auxReferenceAudioPaths.join('\n'))}${btn('pick-reference-set','多选主/辅助音频')}${btn('pick-audios','多选辅助')}<button type="submit" class="primary">本地合成并存入角色语音库</button><audio id="workbench-audio" controls></audio></form><form id="vc-form" class="card"><h4>保留语调 · Seed-VC实验模块</h4><div class="notice warning">RVC选项已移除。Seed-VC需要完整环境/匹配的通用权重；本机转换仍未通过，缺少时明确拒绝。当前接口每次只支持一个目标参考，下方多选池用于切换目标，不声称未消费的参考已融合。</div>${input('installPath','Seed环境（inference.py）',v.installPath)}${btn('pick','选择Seed目录','data-target="installPath" data-kind="directory"')}${input('pythonPath','Seed独立Python',v.pythonPath)}${btn('pick','选择Python','data-target="pythonPath" data-kind="program"')}${input('modelPath','Seed通用checkpoint',v.modelPath)}${btn('pick','选择checkpoint','data-target="modelPath" data-kind="gpt"')}${input('configPath','Seed通用配置',v.configPath)}${input('referenceAudioPath','本次目标参考',v.referenceAudioPath||g.referenceAudioPath)}${area('seedReferences','目标参考池（多选）',(v.referenceAudioPaths||[]).join('\n'))}${btn('pick-seed-refs','多选目标参考')}${input('diffusionSteps','转换步数',v.diffusionSteps,'number')}${input('pitch','整体半音偏移，0保留',v.pitch,'number')}${toggle('allowModelDownload','允许首次通用模型下载',v.allowModelDownload)}<button class="primary" type="submit">保存转换设置</button><hr>${btn('record-voice','开始原始录音')}${btn('stop-record-voice','结束录音')}${btn('pick-vc-input','选择输入录音')}<p id="record-status">仅在本机保存</p>${input('vcInput','输入录音','')}${input('vcTitle','语音标题','我的台词')}${input('vcJa','日文字幕','')}${input('vcZh','中文字幕','')}${btn('convert-voice','转换并保存','','primary')}</form>`;}




