import {visibleSkeletonBounds} from './visibleBounds.js';
export const bodySlot=(name:string)=>/(?:^|_)(head|face|body|chest|waist|hip|belt|leg|calf|foot|neck)(?:_|\d|$)/i.test(name)&&!/weapon|staff|sword|shield|fx|effect|annex|shadow|ear/i.test(name);
function filteredBounds(sk:any,match:(name:string)=>boolean){const held:any[]=[];try{for(const slot of sk.slots)if(slot.attachment&&!match(slot.data.name)){held.push([slot,slot.attachment]);slot.attachment=null;}const vector=()=>({x:0,y:0,set(x:number,y:number){this.x=x;this.y=y;return this;}});const offset=vector(),size=vector();visibleSkeletonBounds(sk,offset,size);return {left:offset.x,right:offset.x+size.x,bottom:offset.y,top:offset.y+size.y,width:size.x,height:size.y};}finally{for(const [s,a]of held)s.attachment=a;}}
export function measureBody(sk:any){let b=filteredBounds(sk,bodySlot);let source='body-slots';if(!Number.isFinite(b.height)||b.height<=0){b=filteredBounds(sk,()=>true);source='fallback-visible';}const feet=filteredBounds(sk,n=>/(?:^|_)foot(?:_|\d|$)/i.test(n));const bottom=Number.isFinite(feet.bottom)?feet.bottom:b.bottom;return {...b,bottom,height:Math.max(1,b.top-bottom),source};}
export function seatContact(sk:any){const waist=filteredBounds(sk,n=>/(?:^|_)(waist|hip|body)(?:_|\d|$)/i.test(n));if(Number.isFinite(waist.bottom)&&waist.height>0)return waist.bottom;const legs=sk.bones.filter((b:any)=>/(?:^|_)(?:[lr]_)?leg$/i.test(b.data.name)&&b.active);if(legs.length)return Math.min(...legs.map((b:any)=>b.worldY-Math.abs(b.data.length)*.35));return measureBody(sk).bottom;}
export interface BodyRect{x:number;y:number;width:number;height:number}
export function bodyWorldRect(window:BodyRect,body:BodyRect):BodyRect{return {x:window.x+body.x,y:window.y+body.y,width:body.width,height:body.height};}
export function clampBodyPosition(x:number,y:number,body:BodyRect,area:BodyRect){return {x:Math.max(area.x-body.x,Math.min(area.x+area.width-body.x-body.width,x)),y:Math.max(area.y-body.y,Math.min(area.y+area.height-body.y-body.height,y))};}
export type Surface='bottom'|'left'|'top'|'right';
export const surfaceDegrees={bottom:0,left:90,top:180,right:270};
export function edgeStep(contact:{x:number;y:number},surface:Surface,area:BodyRect,distance:number){let x=contact.x,y=contact.y,left=distance,s=surface;const maxX=area.x+area.width,maxY=area.y+area.height;for(let i=0;i<8&&left>0;i++){const available=s==='bottom'?x-area.x:s==='left'?y-area.y:s==='top'?maxX-x:maxY-y;const step=Math.min(Math.max(0,available),left);if(s==='bottom')x-=step;else if(s==='left')y-=step;else if(s==='top')x+=step;else y+=step;left-=step;if(left>0||available<=step){s=s==='bottom'?'left':s==='left'?'top':s==='top'?'right':'bottom';}}return {x,y,surface:s};}
export type Point2={x:number;y:number};
export function convexHull(points:Point2[]):Point2[]{const sorted=points.filter(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)).sort((a,b)=>a.x-b.x||a.y-b.y);if(sorted.length<3)return sorted;const cross=(a:Point2,b:Point2,c:Point2)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);const lower:Point2[]=[],upper:Point2[]=[];for(const p of sorted){while(lower.length>=2&&cross(lower.at(-2)!,lower.at(-1)!,p)<=0)lower.pop();lower.push(p);}for(const p of sorted.slice().reverse()){while(upper.length>=2&&cross(upper.at(-2)!,upper.at(-1)!,p)<=0)upper.pop();upper.push(p);}return lower.slice(0,-1).concat(upper.slice(0,-1));}
export function deploymentHull(sk:any){const points:Point2[]=[];for(const slot of sk.drawOrder){const a=slot.attachment;if(!a||!slot.bone.active||!bodySlot(slot.data.name)||slot.color.a*(a.color?.a??1)<=.001)continue;const vertices:number[]=[];try{if(a.worldVerticesLength){a.computeWorldVertices(slot,0,a.worldVerticesLength,vertices,0,2);}else if(a.offset){a.computeWorldVertices(slot.bone,vertices,0,2);}else continue;for(let i=0;i<vertices.length;i+=2)points.push({x:vertices[i],y:vertices[i+1]});}catch{}}return convexHull(points);}
export function polygonsOverlap(a:Point2[],b:Point2[]){if(a.length<3||b.length<3)return false;for(const polygon of [a,b])for(let i=0;i<polygon.length;i++){const p=polygon[i],q=polygon[(i+1)%polygon.length],axis={x:-(q.y-p.y),y:q.x-p.x};const project=(points:Point2[])=>points.map(v=>v.x*axis.x+v.y*axis.y);const pa=project(a),pb=project(b);if(Math.max(...pa)<=Math.min(...pb)||Math.max(...pb)<=Math.min(...pa))return false;}return true;}
export function rotatedBodyRect(body:BodyRect,anchor:Point2,surface:Surface):BodyRect{const r=surfaceDegrees[surface]*Math.PI/180,points=[{x:body.x,y:body.y},{x:body.x+body.width,y:body.y},{x:body.x+body.width,y:body.y+body.height},{x:body.x,y:body.y+body.height}].map(p=>{const x=p.x-anchor.x,y=p.y-anchor.y;return {x:anchor.x+Math.cos(r)*x-Math.sin(r)*y,y:anchor.y+Math.sin(r)*x+Math.cos(r)*y};});const xs=points.map(p=>p.x),ys=points.map(p=>p.y);return {x:Math.min(...xs),y:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)};}
export function pointInPolygon(point:Point2,polygon:Point2[]){let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if(((a.y>point.y)!==(b.y>point.y))&&(point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y)+a.x))inside=!inside;}return inside;}
