import {existsSync,readdirSync,statSync} from 'node:fs';import path from 'node:path';import type {Config} from './config.js';import {roleReferenceConfig} from './roleSpeech.js';
export type DetectionSection='local-tts'|'references'|'bailian'|'asr'|'workbench'|'llm'|'external-realtime';
function filesAt(dir:string,extension:string,depth=4):string[]{if(!existsSync(dir)||depth<0)return [];const out:string[]=[];for(const item of readdirSync(dir,{withFileTypes:true})){if(item.isSymbolicLink())continue;const file=path.join(dir,item.name);if(item.isFile()&&item.name.toLowerCase().endsWith(extension))out.push(file);else if(item.isDirectory()&&depth>0&&!['env','node_modules','.git','__pycache__'].includes(item.name))out.push(...filesAt(file,extension,depth-1));}return out;}
export function detectLocalConfig(c:Config,appRoot:string,builtinRoot:string,section:DetectionSection='local-tts'){
 const next=structuredClone(c),notes:string[]=[],missing:string[]=[];const p=next.speech.gptSovits;
 if(['local-tts','workbench'].includes(section)){
  const candidates=[p.installPath,path.join(appRoot,'speech-runtime/GPT-SoVITS'),path.join(appRoot,'release/Amiya-MVP/resources/app/speech-runtime/GPT-SoVITS')];
  const install=candidates.find(d=>d&&existsSync(path.join(d,'api_v2.py')));if(install){p.installPath=install;const python=[p.pythonPath,...['env/python.exe','runtime/python.exe','env/Scripts/python.exe','.venv/Scripts/python.exe'].map(r=>path.join(install,r))].find(f=>f&&existsSync(f));if(python)p.pythonPath=python;else missing.push('包内Python');
  const modelRoot=path.join(install,'GPT_SoVITS/pretrained_models'),gpts=filesAt(modelRoot,'.ckpt'),sovits=filesAt(modelRoot,'.pth');if(!p.gptModelPath||!existsSync(p.gptModelPath))p.gptModelPath=gpts.find(f=>f.includes('gsv-v2final'))||gpts[0]||'';if(!p.sovitsModelPath||!existsSync(p.sovitsModelPath))p.sovitsModelPath=sovits.find(f=>/s2G2333k\.pth$/i.test(f))||sovits.find(f=>f.includes('gsv-v2final'))||sovits[0]||'';if(!p.gptModelPath)missing.push('GPT权重.ckpt');if(!p.sovitsModelPath)missing.push('SoVITS权重.pth');p.enabled=!!python&&!!p.gptModelPath&&!!p.sovitsModelPath;if(p.enabled&&next.speech.outputMode==='text-only')next.speech.outputMode='gpt-sovits';notes.push('识别到本地环境；已存在的有效自选路径保留。');}else missing.push('GPT-SoVITS完整环境（包含api_v2.py）');
  try{const u=new URL(p.apiUrl);if(u.protocol!=='http:'||!['127.0.0.1','localhost','[::1]'].includes(u.hostname))throw Error();}catch{p.apiUrl='http://127.0.0.1:9880';}notes.push('API地址为本机设置；需连接检测才称服务就绪。');
 }
 if(['local-tts','references','workbench'].includes(section)){try{const prepared=roleReferenceConfig(next,builtinRoot,next.speech.languageMode==='zh'?'zh':'ja');next.speech.gptSovits=prepared.speech.gptSovits;notes.push('主参考与全部辅助来自当前角色的内置录音，3–10秒合法主参考。');}catch(e:any){missing.push(e.message);}}
 if(section==='asr')notes.push('腾讯AppID/SecretID/SecretKey只能由用户账户提供，无法从电脑推断；静音/RMS为本机默认，不需要自动收费测试。');
 if(section==='external-realtime'){const x=next.speech.externalRealtime;if(x.executablePath&&existsSync(x.executablePath))notes.push('已找到用户选择的外部适配器程序；不会自动启动或宣称协议已连接。');else if(x.executablePath)missing.push('外部适配器程序路径不存在');else notes.push('未选择外部程序；可使用已运行的本地 HTTP/WebSocket 服务。');try{const u=new URL(x.endpoint);if(!['ws:','wss:','http:','https:'].includes(u.protocol))throw Error();}catch{missing.push('外部实时语音端点无效');}}
  if(section==='llm')notes.push('识别服务商预设与保存状态，不读取/回显密钥；模型权限必须查询账号或由用户确认。');
 if(section==='bailian'){const hosts:Record<string,string>={'cn-beijing':'dashscope.aliyuncs.com','ap-southeast-1':'dashscope-intl.aliyuncs.com','us-east-1':'dashscope-us.aliyuncs.com'};if(hosts[next.speech.bailian.region])next.speech.bailian.baseUrl='https://'+hosts[next.speech.bailian.region]+'/api/v1/services/aigc/multimodal-generation/generation';}if(section==='bailian')notes.push('按所选地域匹配官方端点；账号API Key/自有音色ID不能自动猜测。');
 return {config:next,notes,missing,detected:missing.length===0,section};
}
export async function probeLocalApi(current:string){const tried:string[]=[];for(const value of [...new Set([current,'http://127.0.0.1:9880','http://127.0.0.1:9883'])]){try{const u=new URL(value);if(u.protocol!=='http:'||!['127.0.0.1','localhost','[::1]'].includes(u.hostname))continue;tried.push(u.origin);const r=await fetch(u.origin+'/openapi.json',{signal:AbortSignal.timeout(800),redirect:'error'}),j:any=await r.json();if(r.ok&&j.paths?.['/tts'])return {ready:true,apiUrl:u.origin,tried};}catch{}}return {ready:false,apiUrl:current,tried};}
