import {migrateFootQuestionDefault} from './footQuestionPolicy.js';
import {defaultDeploymentBinding} from './deploymentPolicy.js';
import {cloneDefaultConfig,mergeConfig,type AppConfig} from '../../../packages/contracts/src/index.js';
import type {VoiceTrainingProfile} from './voiceTraining.js';
import {emptyFavorites,normalizeFavorites,type FavoritesConfig} from './favorites.js';
export type Config=AppConfig & {
 profiles:Record<string,any>;voiceTraining:Record<string,VoiceTrainingProfile>;favorites:FavoritesConfig;autoChatMemory:boolean;behaviour:{defaultsRevision:number;actionSpeeds:Record<string,number>;actionGroup:string;customActionIds:string[];actionVoiceEnabled:boolean;actionVoiceRandomPool:boolean;actionVoiceChance:number;actionVoiceBindings:Record<string,string>;actionVoicePools:Record<string,string[]>;workshopIdleVoiceIds:string[];voiceGroup:string;customVoiceIds:string[];animationSpeed:number;clickBindings:Record<string,{action:string;voiceId:string;actionIds?:string[];voiceIds?:string[]}>};voiceChanger:{engine:'rvc'|'seed-vc';referenceAudioPath:string;referenceAudioPaths:string[];configPath:string;allowModelDownload:boolean;diffusionSteps:number;installPath:string;pythonPath:string;modelPath:string;indexPath:string;pitch:number;indexRate:number;protect:number;f0Method:string};
 assets:{root:string;view:string;group:string;customId:string}; alerts:{enemyId:string;enemyActionGroup:'auto'|'基建'|'战斗'|'自定义';forceShowPet:boolean;morningEnabled:boolean;morningTime:string;lunchEnabled:boolean;lunchTime:string;nightEnabled:boolean;nightTime:string;waterEnabled:boolean;waterIntervalMinutes:number;pomodoroEnabled:boolean;focusMinutes:number;breakMinutes:number;pomodoroCycles:number;quietInFullscreen:boolean;stoneBugEnabled:boolean;stoneBugIntervalMinutes:number};
 ui:AppConfig['ui'] & {bubble:{image:string;background:string;color:string;fontSize:number;minWidth:number;maxWidth:number;width:number;height:number;padding:number};bubbleImageUrl?:string;edgeWalkEnabled:boolean;normalizedBodyHeight:number;closePetsWithControl:boolean;maxFps:number;bottomMargin:number;gravity:boolean;windowEdges:boolean;opacity:number;manualMode:boolean;reducedMotion:boolean;shadow:boolean;clickThrough:boolean;autoStart:boolean;position:{x:number;y:number}|null;touchBattleAnimations:boolean;idleEnabled:boolean;idleSpeechEnabled:boolean;idleSpeechIntervalMs:number;hoverDelayMs:number;randomMinMs:number;randomMaxMs:number};
 speech:AppConfig['speech'] & {languageMode:'ja'|'zh'|'mixed';autoLanguageReference:boolean;replyEnabled:boolean;showText:boolean;subtitleSize:number;externalRealtime:AppConfig['speech']['externalRealtime'];gptSovits:AppConfig['speech']['gptSovits'] & {apiUrl:string;promptText:string;promptLanguage:string;speed:number;pythonPath:string;gptModelPath:string;sovitsModelPath:string;auxReferenceAudioPaths:string[];trainingReferences:Array<{audioPath:string;text:string;language:string;transcriptSource?:string;needsReview?:boolean;reviewed?:boolean}>};tencentAsr:AppConfig['speech']['tencentAsr'] & {language:string;engine:string};bailian:AppConfig['speech']['bailian'] & {language:string}};
 llm:AppConfig['llm'] & {providerLabel:string;temperature:number;dailyCalls:number;visionEnabled:boolean;modelSettings:Record<string,any>};
};
export function defaults():Config {
 const c:any=cloneDefaultConfig();
 c.autoChatMemory=true;c.profiles={};c.voiceTraining={};c.favorites=emptyFavorites();c.behaviour={defaultsRevision:3,actionSpeeds:{},actionGroup:'基建',customActionIds:[],actionVoiceEnabled:true,actionVoiceRandomPool:true,actionVoiceChance:1,actionVoiceBindings:{},actionVoicePools:{},workshopIdleVoiceIds:[],voiceGroup:'日常',customVoiceIds:[],animationSpeed:1,clickBindings:{head_touch:{action:'random',voiceId:'__random__'},face_poke:{action:'Interact',voiceId:'__trust__'},foot_poke:{action:'',voiceId:'__question__'},greet:{action:'',voiceId:'cn_042'},deployment:defaultDeploymentBinding()}};c.voiceChanger={engine:'seed-vc',referenceAudioPath:'',referenceAudioPaths:[],configPath:'',allowModelDownload:false,diffusionSteps:25,installPath:'',pythonPath:'',modelPath:'',indexPath:'',pitch:0,indexRate:0,protect:.33,f0Method:'rmvpe'};
 c.assets={root:'',view:'正面',group:'基建',customId:''};c.alerts={enemyId:'stonebug',enemyActionGroup:'auto',forceShowPet:false,morningEnabled:true,morningTime:'08:00',lunchEnabled:true,lunchTime:'12:00',nightEnabled:true,nightTime:'23:30',waterEnabled:false,waterIntervalMinutes:60,pomodoroEnabled:true,focusMinutes:25,breakMinutes:5,pomodoroCycles:4,quietInFullscreen:true,stoneBugEnabled:false,stoneBugIntervalMinutes:30};
 c.ui={...c.ui,selectedSkin:'Amiya-原皮',bubble:{image:'',background:'#080c12',color:'#e7f0f4',fontSize:13,minWidth:160,maxWidth:320,width:260,height:0,padding:12},edgeWalkEnabled:true,normalizedBodyHeight:280,closePetsWithControl:false,reducedMotion:false,shadow:true,clickThrough:true,autoStart:false,position:null,maxFps:30,bottomMargin:0,gravity:true,windowEdges:false,opacity:1,manualMode:false,touchBattleAnimations:false,idleEnabled:true,idleSpeechEnabled:true,idleSpeechIntervalMs:45000,hoverDelayMs:1000,randomMinMs:8000,randomMaxMs:18000};
 c.llm={...c.llm,model:'deepseek-flash',provider:'openai-compatible',baseUrl:'https://api.deepseek.com/v1',providerLabel:'DeepSeek',temperature:0.65,dailyCalls:50,visionEnabled:false,modelSettings:{}};
 c.speech={...c.speech,languageMode:'ja',autoLanguageReference:true,replyEnabled:true,showText:true,showJapanese:false,showChinese:true,subtitleSize:13,externalRealtime:{...c.speech.externalRealtime,providerLabel:'自定义实时语音',transport:'websocket',endpoint:'ws://127.0.0.1:8765',executablePath:'',workingDirectory:'',arguments:'',autoStart:false,inputFormat:'pcm16',outputFormat:'json'}};
 c.speech.gptSovits={...c.speech.gptSovits,apiUrl:'http://127.0.0.1:9880',promptText:'',promptLanguage:'ja',speed:1,pythonPath:'',gptModelPath:'',sovitsModelPath:'',auxReferenceAudioPaths:[],trainingReferences:[]};
 c.speech.tencentAsr={...c.speech.tencentAsr,silenceMs:1800,maxRecordingMs:60000,language:'zh-CN',engine:'16k_zh'};
 c.speech.bailian={...c.speech.bailian,language:'Japanese',model:'qwen3-tts-flash',voiceId:'Cherry'};
 return c;
}
export function normalizeConfig(input:any):Config {
 const d=defaults(),x=input??{};const c:any=mergeConfig(x);c.autoChatMemory=x.autoChatMemory??d.autoChatMemory;c.favorites=normalizeFavorites(x.favorites||d.favorites);
 for(const k of ['persona','llm','permissions','ui','assets','behaviour','voiceChanger','profiles','alerts'])c[k]={...(d as any)[k],...x[k]};c.llm.visionEnabled=!!x.llm?.visionEnabled;c.llm.modelSettings=x.llm?.modelSettings&&typeof x.llm.modelSettings==='object'&&!Array.isArray(x.llm.modelSettings)?x.llm.modelSettings:{};c.voiceTraining={...d.voiceTraining,...x.voiceTraining};
 c.speech={...d.speech,...x.speech};c.behaviour.workshopIdleVoiceIds=Array.isArray(c.behaviour.workshopIdleVoiceIds)?[...new Set(c.behaviour.workshopIdleVoiceIds.filter((v:any)=>typeof v==='string'))]:[];c.speech.externalRealtime={...d.speech.externalRealtime,...x.speech?.externalRealtime};for(const k of ['gptSovits','tencentAsr','bailian'])c.speech[k]={...(d.speech as any)[k],...x.speech?.[k]};
 if(!x.assets?.group)c.assets.group=x.assets?.view==='正面'?'战斗':'基建';c.assets.view='正面';
 if(x.persona?.personality==='温柔且有责任感，能够体会他人的感受；面对困难时保持希望，不把悲伤夸张成每轮对话的固定主题。'){c.persona={...c.persona,personality:d.persona.personality,speechHabits:d.persona.speechHabits,examples:d.persona.examples};}
 if(c.voiceChanger.engine==='rvc')c.voiceChanger.engine='seed-vc';c.ui.bubble={...d.ui.bubble,...x.ui?.bubble};c.behaviour.defaultsRevision=x.behaviour?(x.behaviour.defaultsRevision||0):2;c.behaviour.clickBindings={...d.behaviour.clickBindings,...x.behaviour?.clickBindings};for(const b of Object.values(c.behaviour.clickBindings) as any[]){b.actionIds=Array.isArray(b.actionIds)?[...new Set(b.actionIds)].slice(0,300):[];b.voiceIds=Array.isArray(b.voiceIds)?[...new Set(b.voiceIds)].slice(0,100):[];}c.behaviour=migrateFootQuestionDefault(c.behaviour);c.speech.showJapanese=false;c.memories=[];return c;
}
export function validateConfig(c:Config):Config {
 const bound=(n:any,min:number,max:number,label:string)=>{if(!Number.isFinite(Number(n))||Number(n)<min||Number(n)>max)throw new Error(`${label}应为 ${min}–${max}`);};
 bound(c.llm.maxContextTokens,512,32768,'上下文');bound(c.llm.maxOutputTokens,64,4096,'输出长度');bound(c.llm.dailyCalls,1,10000,'每日调用上限');bound(c.llm.temperature,0,2,'随机度');
 for(const value of [c.ui.bubble.background,c.ui.bubble.color])if(!/^#[0-9a-f]{6}$/i.test(value))throw Error('气泡颜色必须为六位HEX');bound(c.ui.bubble.fontSize,10,28,'气泡字号');bound(c.ui.bubble.minWidth,120,520,'气泡最小宽');bound(c.ui.bubble.maxWidth,c.ui.bubble.minWidth,520,'气泡最大宽');bound(c.ui.bubble.width,c.ui.bubble.minWidth,c.ui.bubble.maxWidth,'气泡当前宽');bound(c.ui.bubble.height,0,1200,'气泡当前高');bound(c.ui.bubble.padding,0,30,'气泡留白');bound(c.ui.randomMinMs,2000,300000,'闲置动作间隔');bound(c.ui.randomMaxMs,c.ui.randomMinMs,540000,'闲置随机上限');bound(c.ui.idleSpeechIntervalMs,15000,900000,'闲置台词间隔');bound(c.ui.scale,.4,1.7,'角色缩放');bound(c.ui.maxFps,15,60,'帧率');bound(c.ui.bottomMargin,0,500,'下边界');bound(c.ui.opacity,.2,1,'透明度');bound(c.speech.subtitleSize,10,30,'字幕字号');
 bound(c.speech.tencentAsr.silenceMs,300,10000,'静音时长');bound(c.speech.tencentAsr.volumeThreshold,.001,1,'音量阈值');bound(c.speech.tencentAsr.maxRecordingMs,3000,120000,'录音时长');bound(c.speech.gptSovits.speed,.5,2,'语速');
 if(!['auto','基建','战斗','自定义'].includes(c.alerts.enemyActionGroup))throw new Error('敌人动作组无效');if(typeof c.alerts.enemyId!=='string'||!c.alerts.enemyId.trim())throw new Error('敌人单位无效');bound(c.speech.bailian.dailyCharBudget,0,1e7,'云端日额度');bound(c.alerts.waterIntervalMinutes,5,1440,'喝水间隔');bound(c.alerts.focusMinutes,1,240,'专注时长');bound(c.alerts.breakMinutes,1,120,'休息时长');bound(c.alerts.pomodoroCycles,1,20,'番茄钟循环次数');bound(c.alerts.stoneBugIntervalMinutes,5,1440,'源石虫间隔');bound(c.speech.bailian.monthlyCharBudget,0,1e8,'云端月额度');
 for(const speed of Object.values(c.behaviour.actionSpeeds))bound(speed,.25,2,'单独动作速度');bound(c.behaviour.animationSpeed,.25,2,'动作速度');bound(c.behaviour.actionVoiceChance,0,1,'动作语音概率');bound(c.voiceChanger.pitch,-24,24,'变声音高');bound(c.voiceChanger.indexRate,0,1,'检索比例');bound(c.voiceChanger.protect,0,.5,'气息保护');
 if(!['mock','openai-compatible'].includes(c.llm.provider))throw new Error('未知LLM类型');if(!['text-only','gpt-sovits','trained-voice','bailian'].includes(c.speech.outputMode))throw new Error('未知语音路由');
 if(!['ja','zh','mixed'].includes(c.speech.languageMode))throw new Error('发声语言应为日语、中文或混合');
 if(!['seed-vc','rvc'].includes(c.voiceChanger.engine))throw new Error('未知变声引擎');bound(c.voiceChanger.diffusionSteps,4,100,'转换步数');
 if(!Number.isInteger(c.voiceChanger.pitch))throw new Error('变声音高偏移使用整数半音');
 if(!['rmvpe','pm'].includes(c.voiceChanger.f0Method))throw new Error('RVC音高算法应为rmvpe或pm');
 if(!['auto','cpu','cuda'].includes(c.speech.gptSovits.device))throw new Error('推理设备无效');if(!['websocket','http'].includes(c.speech.externalRealtime.transport))throw new Error('外部实时语音传输协议无效');if(!['pcm16','wav'].includes(c.speech.externalRealtime.inputFormat))throw new Error('外部实时语音输入格式无效');if(!['json','text'].includes(c.speech.externalRealtime.outputFormat))throw new Error('外部实时语音输出格式无效');if(c.speech.externalRealtime.enabled){try{const u=new URL(c.speech.externalRealtime.endpoint);if(!['ws:','wss:','http:','https:'].includes(u.protocol))throw Error();}catch{throw new Error('外部实时语音端点必须是 ws/wss/http/https 地址');}}
 if(c.persona.personality.length>8000||c.persona.addressJa.length>100)throw new Error('人设或称呼过长');
 c.favorites=normalizeFavorites(c.favorites);for(const name of ['allowedApplications','allowedDirectories']as const){if(!Array.isArray(c.permissions[name])||c.permissions[name].some(x=>typeof x!=='string'))throw new Error('权限白名单无效');}
 c.speech.gptSovits.auxReferenceAudioPaths=[...new Set(c.speech.gptSovits.auxReferenceAudioPaths)].slice(0,100);
 if(!Array.isArray(c.speech.gptSovits.trainingReferences)||c.speech.gptSovits.trainingReferences.length>100)throw new Error('训练参考最多100条');
 c.permissions.requireConfirmation=true;c.permissions.maxSteps=Math.max(1,Math.min(6,Number(c.permissions.maxSteps)||5));return c;
}

export function syncActiveProfile(c:Config):Config { const key=c.assets.customId||'amiya_caster'; return {...c,profiles:{...c.profiles,[key]:{...(c.profiles[key]||{}),autoChatMemory:c.autoChatMemory,persona:structuredClone(c.persona),behaviour:structuredClone(c.behaviour),speech:structuredClone(c.speech),voiceChanger:structuredClone(c.voiceChanger)}}}; }

