import { spawn } from 'node:child_process';
import { existsSync,realpathSync,writeFileSync,readFileSync,copyFileSync,statSync } from 'node:fs';
import path from 'node:path';
const actions=new Set(['open_allowed_app','open_allowed_url','read_allowed_file','write_allowed_file_with_confirmation','type_in_notepad']);
export function validateTool(r:any,p:any){if(!p.enabled||p.emergencyStop)throw new Error('电脑权限关闭或已紧急停止');if(!r||!actions.has(r.action)||typeof r.args!=='object'||!r.args)throw new Error('工具不在允许列表');if(JSON.stringify(r).length>24000)throw new Error('工具参数过长');return r;}
export function resolveAllowedPath(target:string,roots:string[]){if(!target||!path.isAbsolute(target))throw new Error('必须指定绝对路径');const lexical=path.resolve(target);const canonical=existsSync(lexical)?realpathSync(lexical):path.join(realpathSync(path.dirname(lexical)),path.basename(lexical));if(!roots.some(root=>{if(!existsSync(root))return false;const real=realpathSync(root);const rel=path.relative(real,canonical);return rel!==''&&!rel.startsWith('..')&&!path.isAbsolute(rel);})){throw new Error('路径不在许可目录，或经过链接越界');}return canonical;}
export async function executeTool(r:any,p:any,signal:AbortSignal){validateTool(r,p);if(signal.aborted)throw new Error('已停止');const a=r.args;
 if(r.action==='read_allowed_file'){const f=resolveAllowedPath(a.path,p.allowedDirectories);if(statSync(f).size>100000)throw new Error('首版限制读取100KB文本');return {evidence:{path:f,text:readFileSync(f,'utf8').slice(0,2000)}};}
 if(r.action==='write_allowed_file_with_confirmation'){const f=resolveAllowedPath(a.path,p.allowedDirectories);if(['.exe','.ps1','.bat','.cmd','.js','.vbs','.lnk','.dll','.reg','.hta'].includes(path.extname(f).toLowerCase()))throw new Error('不允许写入可执行脚本');if(typeof a.content!=='string'||a.content.length>20000)throw new Error('文本最多20000字');if(existsSync(f))copyFileSync(f,f+'.amiya-backup-'+Date.now());if(signal.aborted)throw new Error('已停止');writeFileSync(f,a.content,'utf8');return {evidence:{path:f,contentMatches:readFileSync(f,'utf8')===a.content}};}
 if(r.action==='open_allowed_url'){const u=new URL(a.url);if(u.protocol!=='https:')throw new Error('只允许https网页');return {url:u.href};}
 if(r.action==='open_allowed_app'){if(!p.allowedApplications.includes(a.appId))throw new Error('程序不在白名单');const exe=a.appId==='notepad'?path.join(process.env.WINDIR||'C:\\Windows','System32','notepad.exe'):a.appId;if(!existsSync(exe)||!exe.toLowerCase().endsWith('.exe'))throw new Error('白名单程序必须是有效exe路径或notepad');const ch=spawn(exe,[],{windowsHide:false,detached:true,stdio:'ignore'});await new Promise<void>((resolve,reject)=>{ch.once('spawn',()=>resolve());ch.once('error',reject);});ch.unref();return {evidence:{pid:ch.pid,executable:exe,spawned:true}};}
 if(r.action==='type_in_notepad'){
 if(!p.allowedApplications.includes('notepad'))throw new Error('请在程序白名单加入 notepad');if(typeof a.text!=='string'||a.text.length>2000)throw new Error('记事本输入最多2000字');
 const ps=String.raw`Add-Type -AssemblyName UIAutomationClient; Add-Type -AssemblyName UIAutomationTypes; $proc=@(Get-Process notepad -ErrorAction SilentlyContinue|Where-Object {$_.MainWindowHandle -ne 0}); if($proc.Count -ne 1){throw 'Require exactly one Notepad window'}; $root=[System.Windows.Automation.AutomationElement]::FromHandle($proc[0].MainWindowHandle); $c=[System.Windows.Automation.PropertyCondition]::new([System.Windows.Automation.AutomationElement]::ControlTypeProperty,[System.Windows.Automation.ControlType]::Document); $e=$root.FindFirst([System.Windows.Automation.TreeScope]::Descendants,$c); if($null -eq $e){$c=[System.Windows.Automation.PropertyCondition]::new([System.Windows.Automation.AutomationElement]::ControlTypeProperty,[System.Windows.Automation.ControlType]::Edit);$e=$root.FindFirst([System.Windows.Automation.TreeScope]::Descendants,$c)}; if($null -eq $e){throw 'No document control'}; $p=$e.GetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern); $payload=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($env:AMIYA_PAYLOAD));$p.SetValue($payload); if($p.Current.Value -ne $payload){throw 'Verification failed'}; @{pid=$proc[0].Id;verified=$true;method='UIA ValuePattern'}|ConvertTo-Json -Compress`;
 const code=Buffer.from('$ErrorActionPreference="Stop";'+ps,'utf16le').toString('base64');const result=await new Promise<string>((resolve,reject)=>{const ch=spawn(path.join(process.env.WINDIR||'C:\\Windows','System32','WindowsPowerShell','v1.0','powershell.exe'),['-NoProfile','-NonInteractive','-EncodedCommand',code],{windowsHide:true,env:{...process.env,AMIYA_PAYLOAD:Buffer.from(a.text,'utf8').toString('base64')},signal});let out='';let err='';const timer=setTimeout(()=>{ch.kill();reject(new Error('UIA 15秒超时，已停止'));},15000);ch.stdout.on('data',b=>out+=b.toString());ch.stderr.on('data',b=>err+=b.toString());ch.on('error',reject);ch.on('close',n=>{clearTimeout(timer);n===0?resolve(out):reject(new Error('当前记事本不支持安全UIA写入；没有使用盲目按键替代。'));});});return {evidence:JSON.parse(result)};
 }
 throw new Error('未实现工具');}